packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.19.0
  prettier: ^3.4.2
  typescript: ^5.7.3
  husky: ^9.1.7
  lint-staged: ^15.4.3
  tailwindcss: 3.4.4
  nativewind: ^4.1.23

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  jest29:
    "@jest/globals": ^29.7.0
    "@types/jest": ^29.5.14
    jest: 29.7.0
    ts-jest: ^29.2.5
  storybook8:
    "@storybook/addon-actions": ^8.5.3
    "@storybook/addon-a11y": ^8.5.3
    "@storybook/addon-controls": ^8.5.3
    "@storybook/addon-essentials": ^8.5.3
    "@storybook/addon-interactions": ^8.5.3
    "@storybook/addon-ondevice-actions": ^8.5.3
    "@storybook/addon-ondevice-backgrounds": ^8.5.3
    "@storybook/addon-ondevice-controls": ^8.5.3
    "@storybook/addon-ondevice-notes": ^8.5.3
    "@storybook/addon-react-native-web": ^0.0.23
    "@storybook/nextjs": ^8.5.3
    "@storybook/react": ^8.5.3
    "@storybook/react-native": ^8.5.3
    "@storybook/react-webpack5": ^8.5.3
    "@storybook/test": ^8.5.3
    "@storybook/test-runner": ^0.21.0
    "chromatic": ^11.25.2
    "storybook": ^8.5.3
