name: 'Chromatic'
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.chromatic.outputs.code }}
      storybookUrl: ${{ steps.chromatic.outputs.storybookUrl }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: ${{ needs.deploy.outputs.code == 0 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run Storybook tests
        run: npm run storybook:test -- --url ${{ needs.deploy.outputs.storybookUrl }}
